#!/usr/bin/env bash

set -Eeo pipefail

##TODO: 
# 1. 检测执行程序是否存在
# 2. 使用普通用户运行服务

config_check() {
    local opt=$1
    if [ "$opt" = "base" ]; then
        if [ -z "$DEPLOY_PATH" ]; then
            echo 'deploy path no set, use default path "/apps".'
            DEPLOY_PATH=/apps
        else
            echo "deploy path $DEPLOY_PATH"
            DEPLOY_PATH=${DEPLOY_PATH%*\/}
        fi
        chown -R zceo "$DEPLOY_PATH"

	## 外部存储挂载目录.
	if [ -n "$STORAGE_MOUNT" ]; then
            if [ -d $DEPLOY_PATH/storage/upload ]; then
                mv $DEPLOY_PATH/storage/upload{,_old}
	    fi
	    ln -snf $STORAGE_MOUNT $DEPLOY_PATH/storage/upload
        fi

    fi

    if [ "$opt" = "thrift" ]; then
        if [ -z "$SERVICE_THRIFT_PORT" ]; then
            echo 'thrift use default port ":8090".'
            SERVICE_THRIFT_PORT=8090
        fi
        echo "thrift listen port $SERVICE_THRIFT_PORT"
    fi

    if [ "$opt" = "swoole" ]; then
        if [ -z "$SERVICE_SWOOLE_PORT" ]; then
            echo 'swoole use default port ":8080".'
            SERVICE_SWOOLE_PORT=8080
        fi
        echo "swoole listen port $SERVICE_SWOOLE_PORT"
    fi
}

if [ "${1:0:1}" = '-' ]; then
	set -- php "$@"
fi

## 接收参数 $1 为 production 时将进入 swoole 相关服务器运行模式.
if [ "$1" = "production" ]; then
    rm -rf /var/tmp/*
    config_check base
    if [ "$SERVICE_THRIFT" = 1 ] || [ "$SERVICE_THRIFT" = "on" ]; then
        echo "Start thrift service..."
        config_check thrift
        su-exec zceo php $DEPLOY_PATH/vendor/bin/cerpc-swoole -h0.0.0.0 -p$SERVICE_THRIFT_PORT -d
    fi

    if [ "$SERVICE_TASK" = 1 ] || [ "$SERVICE_TASK" = "on" ]; then
	    if [ "$SERVICE_TASK_DEBUG" = 1 ] || [ "$SERVICE_TASK_DEBUG" = "on" ]; then
      	        echo "Start task service..."
                su-exec zceo php $DEPLOY_PATH/vendor/bin/process -d

	    fi
      	        echo "Start task service..."
                su-exec zceo php $DEPLOY_PATH/vendor/bin/process -d >/dev/null
    fi

    if [ "$SERVICE_SWOOLE" = 1 ] || [ "$SERVICE_SWOOLE" = "on" ]; then
        echo "Start http service..."
        config_check swoole
        exec su-exec zceo php $DEPLOY_PATH/vendor/bin/lumen-swoole -h0.0.0.0 -p$SERVICE_SWOOLE_PORT
    fi
fi

exec "$@"
